### ISSUE TITLE
Rule Login PRODI

### ISSUE THREAD

**Issue by bening14** [solusi-cipta-media/tracer_univradenrahmad#1]
1. Dibuatkan level untuk login, saat ini hanya ada 2 yaitu user dan admin saja, nanti menjadi 3 yaitu : User, Kaprodi, dan Admin (Super User)
2. Untuk level kaprodi, hanya bisa melihat data sesuai dengan prodinya saja
3. untuk admin/superuser biarkan seperti sekarang, bisa melihat semua aktivitas.

**Comment by bening14** [comment]
MENU KAPRODI
===============
1. Grafik total tracer prodi (dashboard) dihilangkan
2. Card total prodi (dashboard) dihilangkan
3. Menu Master prodi dihilangkan
4. Menu Analisa + Laporan disesuaikan sesuai data masing-masing alumni prodi
5. Laporan tracer, Card prodi dihilangkan, Perkembangan tracer study perprodi dihilangkan
6. Halaman setting, add user dihilangkan saja
7. Logo diganti UNIRA (Cari di internet dulu)
8. Teks Judul Tracer juga di ganti menjadi Universitas Raden Rahmad

**Comment by nggepe** [comment]
baik pak
