### ISSUE TITLE
Additional menu Master Alumni

### ISSUE THREAD

**Issue by bening14** [solusi-cipta-media/tracer_univradenrahmad#4]
1. Buatkan menu Master Alumni
2. Isinya tentang datatable alumni dan tombol menambahkan alumni (bisa upload excel)
3. menu menambahkan alumni ini ada di menu admin dan kaprodi
4. khusus untuk login kaprodi, data alumni dikunci prodinya. misal kalau yang upload kaprodi BK maka otomatis data yang terupload alumninya sebagai alumni BK.
5. untuk menu Admin, data alumni yang diupload, data program studi berdasarkan dropdown/pilihan input by admin.
6. untuk database, silahkan dikonsep sendiri mas, simple saja, kalau bayangan saya,, [ id, kode_prodi, nama_prodi, nim, nama_alumni ]

**Comment by nggepe** [comment]
baik pak, mohon maaf baru ngerjakan hari ini. 🙏
