### ISSUE TITLE
Merapihkan menu kaprodi

### ISSUE THREAD

**Issue by bening14** [solusi-cipta-media/tracer_univradenrahmad#7]
1. Tambah CARD Total Tracer seperti yang ada di dashboard superuser, hanya saja ditambahkan where session kaprodi, jadi hanya kalkulasi jumlah sesuai dengan session kaprodi yang login. gambar seperti dibawah

![image](https://user-images.githubusercontent.com/55275901/130456766-ea47a45a-7e26-43bd-b51e-514026d564bf.png)

[TOTAL TRACER]

Jadi informasi Card yang tersedia adalah TOTAL TRACER dan USERS

2. Delete Grafik OVERVIEW TOTAL TRACER - PRODI

![image](https://user-images.githubusercontent.com/55275901/130456766-ea47a45a-7e26-43bd-b51e-514026d564bf.png)

Karena isi grafik ini adalah informasi prodi mana saja yang alumninya sudah melakukan tracer, jadi sudah tidak relevan lagi jika ditampilkan di dashboard kaprodi.

3. Pada tabel Alumni, hanya ditampilkan data alumni yang sesuai dengan login atau session kaprodinya, misal saya login dengan prodi Teknik Informatika, berarti data yang ditampilkan ditabel adalah alumni-alumni Teknik Informatika saja.

![image](https://user-images.githubusercontent.com/55275901/130457430-0ed8832b-2a03-4199-99d0-70b422d1f338.png)

Gambar diatas menggambarkan alumni dari dua prodi yang berbeda, seharusnya data yang ditampilkan hanya sesuai session kaprodi.

4. Belum ada Prevent jika input NIM yang sudah ada di database, karena pada dasarnya NIM mahasiswa adalah unik dan itu menjadi parameter utama untuk tracer, maka ketika mendaftarkan dilarang ada double NIM.

![image](https://user-images.githubusercontent.com/55275901/130457721-2e275753-e125-4dfe-a866-27d6e906589d.png)

**Comment by nggepe** [comment]
siap pak, maaf baru bisa ngerjakan. dari pagi ngurusi lamaran. 🙏

**Comment by bening14** [comment]
Calon mantenn 😊, sudah kebeli semua mas?

**Comment by nggepe** [comment]
alhamdulillah pak, sisa mas kawin dan surat-surat. 😁

**Comment by nggepe** [comment]
pak, point 1 dan 2 ada di #8  ya pak.

**Comment by nggepe** [comment]
point 3 dan 4 ada di #9 ya pak.

**Comment by nggepe** [comment]
pak, ini sudah saya selesaikan, saya close by merge ya pak
